import { type Session } from "next-auth";
import { SessionProvider } from "next-auth/react";
import { type AppType } from "next/app";
import { api } from "~/utils/api";
import Head from 'next/head';
import "~/styles/globals.css";
import { Navbar } from "~/utils/components/navigation/navbar";
import { Footer } from "~/utils/components/navigation/footer";
import { SideNav } from "~/utils/components/navigation/sidenav";
import Header from '~/utils/components/base/header';
import { useState } from "react";
import { DarkModeProvider } from "~/utils/components/dark-mode/dark-mode-context";
import Script from "next/script";
import {HarmonySetup} from 'harmony-ai-editor';
import { fonts } from "~/utils/fonts";


const MyApp: AppType<{ session: Session | null }> = ({
  Component,
  pageProps: { session, ...pageProps },
}) => {
  const [pos, setPos] = useState<{x: number, y: number}>({x: 1160, y: 74});
  const onPointerMove = (e: React.PointerEvent) => {
    setPos({x: e.clientX, y: e.clientY});
  }
  return (<>
    <SessionProvider session={session}>
      <Head>
        <title>Braydon Jones</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
				<script async={'async' as unknown as boolean} src="https://static.mobilemonkey.com/js/mm_0bfd2199-8eab-40ac-8140-ed9eabcfb716-34541796.js"></script>
      </Head>
      <DarkModeProvider>
        <div onPointerMove={onPointerMove}>
          <div className="pointer-events-none fixed inset-0 -z-10 h-full transition duration-300 bg-white dark:bg-slate-900" ></div>
          <div onPointerMove={onPointerMove} className="pointer-events-none fixed inset-0 z-50 transition duration-300 hidden dark:block" style={{background: `radial-gradient(600px at ${pos.x}px ${pos.y}px, rgba(29, 78, 216, 0.15), transparent 80%)`}}></div>
          <main className="mx-auto min-h-screen max-w-screen-xl px-6 py-12 font-sans md:px-12 md:py-20 lg:px-24 lg:py-0 text-slate-700 dark:text-slate-400 ">
            <Component {...pageProps} />
          </main>
        </div>
      </DarkModeProvider>
      <HarmonySetup repositoryId="5f296668-b002-45d7-89e4-fb303e7e22d6" fonts={fonts}/>
      <Script id='heap-script' type="text/javascript">
      {`window.heapReadyCb=window.heapReadyCb||[],window.heap=window.heap||[],heap.load=function(e,t){window.heap.envId=e,window.heap.clientConfig=t=t||{},window.heap.clientConfig.shouldFetchServerConfig=!1;var a=document.createElement("script");a.type="text/javascript",a.async=!0,a.src="https://cdn.us.heap-api.com/config/"+e+"/heap_config.js";var r=document.getElementsByTagName("script")[0];r.parentNode.insertBefore(a,r);var n=["init","startTracking","stopTracking","track","resetIdentity","identify","getSessionId","getUserId","getIdentity","addUserProperties","addEventProperties","removeEventProperty","clearEventProperties","addAccountProperties","addAdapter","addTransformer","addTransformerFn","onReady","addPageviewProperties","removePageviewProperty","clearPageviewProperties","trackPageview"],i=function(e){return function(){var t=Array.prototype.slice.call(arguments,0);window.heapReadyCb.push({name:e,fn:function(){heap[e]&&heap[e].apply(heap,t)}})}};for(var p=0;p<n.length;p++)heap[n[p]]=i(n[p])};
  heap.load("3924392742");`}
      </Script>
    </SessionProvider>
    </>
  );
};

export default api.withTRPC(MyApp);
