import { type Session } from "next-auth";
import { SessionProvider } from "next-auth/react";
import { type AppType } from "next/app";
import { api } from "~/utils/api";
import Head from 'next/head';
import "~/styles/globals.css";
import { Navbar } from "~/utils/components/navigation/navbar";
import { Footer } from "~/utils/components/navigation/footer";
import { SideNav } from "~/utils/components/navigation/sidenav";
import Header from '~/utils/components/base/header';

const MyApp: AppType<{ session: Session | null }> = ({
  Component,
  pageProps: { session, ...pageProps },
}) => {
  return (
    <SessionProvider session={session}>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="dark">
        <div className="absolute">Button</div>
        <div className="pointer-events-none fixed inset-0 -z-10 h-full transition duration-300 bg-white dark:bg-slate-900" ></div>
        <div className="pointer-events-none fixed inset-0 z-30 transition duration-300 " style={{background: 'radial-gradient(600px at 1160px 74px, rgba(29, 78, 216, 0.15), transparent 80%)'}}></div>
        <main className="mx-auto min-h-screen max-w-screen-xl px-6 py-12 font-sans md:px-12 md:py-20 lg:px-24 lg:py-0 text-slate-700 dark:text-slate-400 ">
          <Component {...pageProps} />
        </main>
      </div>
    </SessionProvider>
  );
};

export default api.withTRPC(MyApp);
